- hosts: lb
  tasks:
  - name: installing haproxy
    package:
      name: "haproxy"
      state: present
  - name: copying the files
    template:
      src: "/root/code/local.cfg.j2"
      dest: "/etc/haproxy/haproxy.cfg"
  - name: starting service
    service:
      name: "haproxy"
      state: restarted
      enabled: true
